### ISSUE TITLE
Can't install Ubuntu 15.04 Final Beta (Beta2)

### ISSUE THREAD

**Issue by NedasPekorius** [marcoDallas/acpi_call_GUI_systemd#1]
cant install on Ubuntu Vivid. I know it runs on Systemd so installed acpi_call_GUI_systemd 
java app gives error wen selecting acpi off string:

fatal: destination path '/usr/local/bin/acpi_call' already exists and is not an empty directory.
make -C /lib/modules/3.19.0-10-generic/build M=/usr/local/bin/acpi_call modules
make[1]: Entering directory '/usr/src/linux-headers-3.19.0-10-generic'
  CC [M]  /usr/local/bin/acpi_call/acpi_call.o
In file included from include/acpi/platform/acenv.h:172:0,
                 from include/acpi/acpi.h:56,
                 from /usr/local/bin/acpi_call/acpi_call.c:9:
include/acpi/platform/aclinux.h:52:2: error: #error "Please don't include <acpi/acpi.h> directly, include <linux/acpi.h> instead."
 #error "Please don't include <acpi/acpi.h> directly, include <linux/acpi.h> instead."
  ^
scripts/Makefile.build:263: recipe for target '/usr/local/bin/acpi_call/acpi_call.o' failed
make[2]: **\* [/usr/local/bin/acpi_call/acpi_call.o] Error 1
Makefile:1394: recipe for target '_module_/usr/local/bin/acpi_call' failed
make[1]: **\* [_module_/usr/local/bin/acpi_call] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.19.0-10-generic'
Makefile:8: recipe for target 'default' failed
make: **\* [default] Error 2
insmod: ERROR: could not load module acpi_call.ko: No such file or directory
cp: cannot create regular file ‘/usr/lib/systemd/system/’: Not a directory
Failed to execute operation: No such file or directory
Process Complete.

**Comment by marcoDallas** [comment]
Hi,

These problems are related directly to acpi_call, not to my Java utility.

By the way, it seems that acpi_call is unable to re-compile the kernel, are
you sure you have installed all the things that are necessary to compile
the kernel (linux-headers and build-essential)? Using the systemd version
you have to install them by yourself.
Il 01/apr/2015 10:39 "NedasPekorius" notifications@github.com ha scritto:

**Comment by marcoDallas** [comment]
Confirmed, this problem is related **directly to acpi_call**, we hope that Michal Kottman will merge the fix soon.
By the way, if you want you can fix this by yourself by following the instructions reported in the following pull requests:

> https://github.com/mkottman/acpi_call/pull/53
> https://github.com/mkottman/acpi_call/pull/52
> https://github.com/mkottman/acpi_call/pull/49

You will find the acpi_call folder in:

```
/usr/local/bin/acpi_call/
```
