### ISSUE TITLE
Build issue with kernel 5.6

### ISSUE THREAD

**Issue by ruathudo** [marcoDallas/acpi_call_GUI_systemd#2]
I tried to install acpi_call in Fedora 32 with kernel 5.6.6 and facing this issue. Could you figure it out? Here is the log:

`Cloning into '/usr/local/bin/acpi_call'...
make -C /lib/modules/5.6.6-300.fc32.x86_64/build M=/usr/local/bin/acpi_call modules
make[1]: Entering directory '/usr/src/kernels/5.6.6-300.fc32.x86_64'
  CC [M]  /usr/local/bin/acpi_call/acpi_call.o
/usr/local/bin/acpi_call/acpi_call.c: In function ‘init_acpi_call’:
/usr/local/bin/acpi_call/acpi_call.c:366:53: error: passing argument 4 of ‘proc_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  366 |                                                     &proc_acpi_operations);
      |                                                     ^~~~~~~~~~~~~~~~~~~~~
      |                                                     |
      |                                                     struct file_operations *
In file included from /usr/local/bin/acpi_call/acpi_call.c:7:
./include/linux/proc_fs.h:64:122: note: expected ‘const struct proc_ops *’ but argument is of type ‘struct file_operations *’
   64 | struct proc_dir_entry *proc_create(const char *name, umode_t mode, struct proc_dir_entry *parent, const struct proc_ops *proc_ops);
      |                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:268: /usr/local/bin/acpi_call/acpi_call.o] Error 1
make[1]: *** [Makefile:1683: /usr/local/bin/acpi_call] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.6.6-300.fc32.x86_64'
make: *** [Makefile:8: default] Error 2
insmod: ERROR: could not load module /usr/local/bin/acpi_call/acpi_call.ko: No such file or directory
chmod: cannot access '/proc/acpi/call': No such file or directory
disabling GPU drivers, please note that if necessary uninstall.sh will also re-enable them
Process Complete.`

Thanks!

**Comment by marcoDallas** [comment]
Hi, thank you for reporting this issue, I will look into it and give you an update soon

**Comment by marcoDallas** [comment]
Hi, the bug should be fixed, could you test it now? you must uninstall the old version before installing the new one https://github.com/marcoDallas/acpi_call_GUI_systemd#to-uninstall

For completeness:
The new version 1.2.1 refers to https://github.com/marcoDallas/acpi_call/ wich is the dependency that was causing this bug, you just need to install acpi_call_GUI_systemd again and it will automatically download the new version of this dependency.

**Comment by ruathudo** [comment]
Hi, I think it is fixed now. Thanks!
